-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 01:34:24 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(20) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Passengers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Passengers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Passengers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `nationality` VARCHAR(45) NULL,
  `passenger_type` ENUM('adult', 'child', 'infant') NULL,
  `bonus_miles` INT NULL,
  `membership_date` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Passengers_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Passengers_User1_idx` ON `mydb`.`Passengers` (`User_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hire_date` DATE NOT NULL,
  `role` VARCHAR(45) NULL,
  `salary` DECIMAL(10,2) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Staff_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Staff_User1_idx` ON `mydb`.`Staff` (`User_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Airports_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Airports_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Airports_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(20) NOT NULL,
  `code` CHAR(5) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Terminals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terminals` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Terminals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `terminal_name` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `capacity` INT NOT NULL,
  `check_in_count` INT NOT NULL,
  `luggage_belts` INT NOT NULL,
  `working_hours` TIME NULL,
  `Airport_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Terminals_Airport_info1`
    FOREIGN KEY (`Airport_info_id`)
    REFERENCES `mydb`.`Airports_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Terminals_Airport_info1_idx` ON `mydb`.`Terminals` (`Airport_info_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Gates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gate_number` VARCHAR(10) CHARACTER SET 'DEFAULT' NOT NULL,
  `floor_level` INT NOT NULL,
  `current_status` ENUM('open', 'closed', 'boarding') NOT NULL,
  `boarding_start_time` DATETIME NOT NULL,
  `Terminals_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Gates_Terminals1`
    FOREIGN KEY (`Terminals_id`)
    REFERENCES `mydb`.`Terminals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Gates_Terminals1_idx` ON `mydb`.`Gates` (`Terminals_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Airlines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Airlines` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Airlines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `safety_rating` DECIMAL(2,1) NOT NULL,
  `fleet_size` INT NOT NULL,
  `contact_email` VARCHAR(100) NOT NULL,
  `maitenance_provider` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Planes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Planes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Planes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `board_number` VARCHAR(20) NOT NULL,
  `seats_capacity` INT NOT NULL,
  `year_production` YEAR NOT NULL,
  `Airlines_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Planes_Airlines1`
    FOREIGN KEY (`Airlines_id`)
    REFERENCES `mydb`.`Airlines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Planes_Airlines1_idx` ON `mydb`.`Planes` (`Airlines_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Flights` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Flights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flight_number` VARCHAR(15) CHARACTER SET 'DEFAULT' NOT NULL,
  `departure_time` DATETIME NOT NULL,
  `arrival_time` DATETIME NOT NULL,
  `Planes_id` INT NOT NULL,
  `Gates_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Flights_Planes1`
    FOREIGN KEY (`Planes_id`)
    REFERENCES `mydb`.`Planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Gates1`
    FOREIGN KEY (`Gates_id`)
    REFERENCES `mydb`.`Gates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Flights_Planes1_idx` ON `mydb`.`Flights` (`Planes_id` ASC) VISIBLE;

CREATE INDEX `fk_Flights_Gates1_idx` ON `mydb`.`Flights` (`Gates_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Maintenance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Maintenance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Maintenance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `check_type` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `last_service_date` DATE NOT NULL,
  `next_service_date` DATE NOT NULL,
  `Staff_id` INT NOT NULL,
  `Planes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Maintenance_Staff1`
    FOREIGN KEY (`Staff_id`)
    REFERENCES `mydb`.`Staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Maintenance_Planes1`
    FOREIGN KEY (`Planes_id`)
    REFERENCES `mydb`.`Planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Maintenance_Staff1_idx` ON `mydb`.`Maintenance` (`Staff_id` ASC) VISIBLE;

CREATE INDEX `fk_Maintenance_Planes1_idx` ON `mydb`.`Maintenance` (`Planes_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tickets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seat_number` VARCHAR(15) CHARACTER SET 'DEFAULT' NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `booking_status` ENUM('confirmed', 'cancelled', 'pending') NOT NULL,
  `Passengers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Tickets_Passengers1`
    FOREIGN KEY (`Passengers_id`)
    REFERENCES `mydb`.`Passengers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Tickets_Passengers1_idx` ON `mydb`.`Tickets` (`Passengers_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Baggage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Baggage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Baggage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag_number` VARCHAR(15) CHARACTER SET 'DEFAULT' NOT NULL,
  `checked_in_date` DATETIME NOT NULL,
  `weight` DECIMAL(5,2) NOT NULL,
  `Tickets_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Baggage_Tickets1`
    FOREIGN KEY (`Tickets_id`)
    REFERENCES `mydb`.`Tickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Baggage_Tickets1_idx` ON `mydb`.`Baggage` (`Tickets_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
